import { test, expect } from '@playwright/test'

test('register, change password, recover and revoke old sessions through real API and MySQL', async ({ page, request }) => {
  const username = `e2e_identity_${Date.now()}`
  const first = 'Local-Identity-1976', second = 'Updated-Identity-1976', third = 'Recovered-Identity-1976'
  await page.goto('pages/login/index')
  await page.getByText('注册账号', { exact: true }).click()
  await page.locator('input[placeholder="你希望被怎样称呼"]').fill('账号联通验收')
  await page.locator('input[placeholder="字母、数字或 . _ -"]').fill(username)
  await page.locator('input[placeholder="至少 10 个字符"]').fill(first)
  const created = page.waitForResponse(response => response.url().endsWith('/user/account/register'))
  await page.getByText('开启我的学习旅程', { exact: true }).click()
  const identity = (await (await created).json()).data
  await expect(page.getByText('保存你的账号恢复码', { exact: true })).toBeVisible()
  await expect(page.locator('.recovery-code')).toHaveText(identity.recovery_code)
  await page.getByText('已保存，继续', { exact: true }).click()
  await page.goto('learning/security/index')
  await expect(page.locator('input[placeholder="字母、数字或 . _ -"]')).toHaveValue(username)
  await page.locator('input[placeholder="输入当前密码"]').fill(first)
  await page.locator('input[placeholder="至少 10 个字符"]').fill(second)
  await page.locator('input[placeholder="再次输入新密码"]').fill(second)
  const changed = page.waitForResponse(response => response.url().endsWith('/identity/credentials'))
  await page.getByText('保存账号密码', { exact: true }).click()
  const fresh = (await (await changed).json()).data
  await expect(page.locator('.recovery-code')).toHaveText(fresh.recovery_code)
  expect((await request.get('api/v1/user/profile', { headers: { Authorization: `Bearer ${identity.token}` } })).status()).toBe(401)
  await page.getByText('已保存，继续', { exact: true }).click()
  await page.goto('pages/profile/index')
  await page.getByText('退出登录', { exact: true }).click()
  await page.getByText('忘记密码', { exact: true }).click()
  await page.locator('input[placeholder="字母、数字或 . _ -"]').fill(username)
  await page.locator('input[placeholder="至少 10 个字符"]').fill(third)
  await page.locator('input[placeholder="再次输入新密码"]').fill(third)
  await page.locator('input[placeholder="注册或账号安全中保存的恢复码"]').fill(fresh.recovery_code)
  await page.getByText('重置密码', { exact: true }).click()
  await expect(page.getByText('密码已重置', { exact: true })).toBeVisible()
  await expect(page.locator('.account-success')).toContainText('原有设备的登录已失效')
  expect((await request.get('api/v1/user/profile', { headers: { Authorization: `Bearer ${fresh.token}` } })).status()).toBe(401)
  const repeated = await request.post('api/v1/user/identity/password/reset', { data: { username, password: first, recovery_code: fresh.recovery_code } })
  expect(repeated.status()).toBe(403)
  await page.locator('input[placeholder="至少 10 个字符"]').fill(third)
  await page.getByText('进入学园', { exact: true }).click()
  await expect(page).toHaveURL(/pages\/index\/index/)
  await page.goto('learning/security/index')
  await expect(page.locator('input[placeholder="字母、数字或 . _ -"]')).toHaveValue(username)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../.local/sdlc/account-linking/security-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '../.local/sdlc/account-linking/security-pc.png', fullPage: true })
})

test('H5 offers WeChat QR and a recoverable provider failure without pretending to log in', async ({ page }) => {
  await page.route('**/api/v1/user/identity/qr/create', route => route.fulfill({ status: 503, json: { code: 503, message: '微信扫码入口尚未发布，请管理员发布对应小程序版本' } }))
  await page.goto('pages/login/index')
  await page.getByText('微信登录', { exact: true }).click()
  await page.getByText('微信扫码登录', { exact: true }).click()
  await expect(page.getByText('微信扫码入口尚未发布，请管理员发布对应小程序版本', { exact: true })).toBeVisible()
  await page.getByText('取消', { exact: true }).click()
  await page.getByText('账号登录', { exact: true }).click()
  await expect(page.getByText('进入学园', { exact: true })).toBeVisible()
  for (const width of [320, 390, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `../.local/sdlc/account-linking/login-${width}.png`, fullPage: true })
  }
})
