import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

test('real account, mobile and desktop appearance', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const missing = await request.get('api/v1/not-a-real-route')
  expect(missing.status()).toBe(404)
  expect(missing.headers()['content-type']).toContain('application/json')
  await page.goto('pages/login/index')
  await expect.poll(() => page.locator('.studio-icon img').last().evaluate(e => {
    const image = e.getBoundingClientRect(), host = e.parentElement!.getBoundingClientRect()
    return image.left >= host.left && image.right <= host.right + 1
  })).toBeTruthy()
  await page.getByText('创建账号', { exact: true }).click()
  await page.locator('input[placeholder="你希望被怎样称呼"]').fill('验收学习者')
  await page.locator('input[placeholder="字母、数字或 . _ -"]').fill(`e2e_${Date.now()}`)
  await page.locator('input[placeholder="至少 10 个字符"]').fill('Local-E2E-Only-1976')
  await page.getByText('开启我的学习旅程', { exact: true }).click()
  await expect(page.locator('.welcome-title')).toBeVisible()
  await page.reload()
  await expect(page.locator('.welcome-title')).toBeVisible()
  await expect(page.locator('.study-panorama')).toBeVisible()
  await expect.poll(() => page.locator('.study-panorama img').evaluate(e => (e as HTMLImageElement).naturalWidth)).toBeGreaterThan(1000)
  expect(await page.locator('.studio').evaluate(e => getComputedStyle(e).backgroundImage)).toBe('none')
  await expect(page.locator('.companion')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await mkdir('../docs/screenshots/h5', { recursive: true })
  await page.screenshot({ path: '../docs/screenshots/h5/01-home.png', fullPage: true })
  await page.getByLabel('外观设置', { exact: true }).click()
  await expect(page.locator('.appearance-dialog')).toBeVisible()
  await page.screenshot({ path: '../.local/appearance-mobile.png', fullPage: true })
  await page.getByLabel('橘晴学妹').click()
  await page.getByText('招手', { exact: true }).click()
  await page.getByLabel('关闭外观设置').click()
  await expect(page.locator('.companion')).toHaveAttribute('data-form', 'orange')
  await expect(page.locator('.companion')).toHaveAttribute('data-pose', '1')
  const animatedRegion = await page.locator('.companion').boundingBox()
  const frame1 = await page.screenshot({ clip: animatedRegion!, animations: 'allow' })
  await page.waitForTimeout(500)
  const frame2 = await page.screenshot({ clip: animatedRegion!, animations: 'allow' })
  expect(frame1.equals(frame2)).toBeFalsy()
  const bounds = await page.locator('.companion').boundingBox()
  await page.mouse.move(bounds!.x + 38, bounds!.y + 66)
  await page.mouse.down()
  await page.mouse.move(50, 410, { steps: 12 })
  await page.mouse.up()
  const saved = await page.evaluate(() => localStorage.getItem('ai-learn:v1:companion-position'))
  expect(saved).toBeTruthy()
  await page.reload()
  await expect(page.locator('.companion')).toBeVisible()
  expect(await page.locator('.companion').evaluate(e => {
    const buddy = e.getBoundingClientRect()
    return [...document.querySelectorAll('.stat, .primary-button, .studio-textarea')].every(node => {
      const box = node.getBoundingClientRect()
      return buddy.right <= box.left || buddy.left >= box.right || buddy.bottom <= box.top || buddy.top >= box.bottom
    })
  })).toBeTruthy()
  await page.locator('textarea').focus()
  await expect(page.locator('.companion')).toBeHidden()
  await page.locator('textarea').blur()
  for (const [id, name] of [['sakura','樱花学园'], ['night','月夜观测室'], ['sea','海盐夏日'], ['forest','森之图书馆'], ['scroll','赤金绘卷']]) {
    await page.getByLabel('外观设置', { exact: true }).click()
    await page.locator('.theme-option').filter({ hasText: name }).click()
    await page.getByLabel('关闭外观设置').click()
    await expect(page.locator(`.theme-${id}`)).toBeVisible()
    if (id === 'night') expect(await page.locator('textarea').evaluate(e => getComputedStyle(e).backgroundColor)).toBe('rgba(0, 0, 0, 0)')
    await page.screenshot({ path: `../docs/screenshots/h5/theme-${id}.png` })
  }
  await page.setViewportSize({ width: 320, height: 568 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.getByLabel('外观设置', { exact: true }).click()
  await page.getByText('减少动效', { exact: true }).scrollIntoViewIfNeeded()
  await page.locator('.setting-row').filter({ hasText: '减少动效' }).locator('input').check()
  await page.getByLabel('关闭外观设置').click()
  await expect(page.locator('.studio')).toHaveClass(/reduced-motion/)
  if (await page.locator('.companion').isVisible()) expect(await page.locator('.companion img').evaluate(e => getComputedStyle(e).animationName)).toBe('none')
  await page.screenshot({ path: '../docs/screenshots/h5/10-small-phone.png' })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '../docs/screenshots/h5/09-desktop.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  expect(errors).toEqual([])
})
