import { test, expect } from '@playwright/test'
import { mkdir, writeFile } from 'node:fs/promises'

test('free placement, tap, long press invitation and owned editable memory work through the actual API', async ({ page, request }) => {
  const response = await request.post('api/v1/user/account/register', { data: { username: `e2e_gesture_${Date.now()}`, password: 'Local-E2E-Only-1976', nickname: '伙伴手札验收' } })
  expect(response.status()).toBe(200)
  const identity = (await response.json()).data
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('pages/login/index')
  await page.evaluate(user => {
    localStorage.setItem('ai-learn:v1:token', JSON.stringify({ data: user.token }))
    localStorage.setItem('ai-learn:v1:user', JSON.stringify({ data: user.user }))
  }, identity)
  await page.goto('pages/index/index')
  const buddy = page.locator('.companion')
  await expect(buddy).toBeVisible()
  const box = (await buddy.boundingBox())!
  await page.mouse.move(box.x + 38, box.y + 60); await page.mouse.down()
  // Leave room for the separate corner target inside the unoccupied sidebar area.
  await page.mouse.move(118, 680, { steps: 16 }); await page.mouse.up()
  await expect(buddy).toHaveAttribute('data-reaction', 'drag')
  await expect(page.locator('.companion-tools')).toHaveCount(0)
  expect((await buddy.boundingBox())!.x).toBeCloseTo(80, 0)
  await page.reload(); await expect(buddy).toBeVisible()
  expect((await buddy.boundingBox())!.x).toBeCloseTo(80, 0)
  await buddy.click({ position: { x: 38, y: 55 } })
  await expect(buddy).toHaveAttribute('data-reaction', 'tap')
  const action = page.getByRole('button', { name: '伙伴操作', exact: true })
  await expect(action).toBeVisible()
  await expect(buddy.locator('button')).toHaveCount(1)
  const actionBox = (await action.boundingBox())!, portraitBox = (await buddy.locator(':scope > img').boundingBox())!
  expect(actionBox.width).toBeLessThanOrEqual(28)
  expect(actionBox.height).toBeLessThanOrEqual(28)
  expect(actionBox.x).toBeGreaterThanOrEqual(portraitBox.x + portraitBox.width + 4)
  expect(actionBox.x + actionBox.width).toBeLessThanOrEqual(1440)
  await page.screenshot({ path: '../docs/screenshots/h5/61-companion-corner-control.png', fullPage: true })
  await action.click()
  await expect(page.getByText('和樱野小满聊天', { exact: true })).toBeVisible()
  await expect(page.getByText('收起伙伴', { exact: true })).toBeVisible()
  await page.getByText('取消', { exact: true }).click()
  await buddy.click({ trial: true, position: { x: 38, y: 20 } })
  await page.evaluate(() => { Math.random = () => 0.1 })
  const placed = (await buddy.boundingBox())!
  await page.mouse.move(placed.x + 38, placed.y + 20); await page.mouse.down()
  await page.waitForTimeout(750); await page.mouse.up()
  await expect(page.getByText('樱野小满的小邀请', { exact: true })).toBeVisible()
  const before = await request.get('api/v1/learning/tasks', { headers: { Authorization: `Bearer ${identity.token}` } })
  expect(before.status()).toBe(200)
  expect((await before.json()).data.items.filter((task: { kind: string }) => task.kind === 'companion')).toHaveLength(0)
  await page.locator('.taro-model__confirm').filter({ hasText: '去聊一会' }).click()
  await expect(page.locator('.room-name')).toHaveText('樱野小满')
  await expect.poll(() => page.locator('.room-portrait img').evaluate(img => (img as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  await page.locator('.room-tabs').getByText('记忆 0', { exact: true }).click()
  await page.locator('input[placeholder="希望伙伴记住的偏好"]').fill('喜欢先看例子再读定义')
  await page.getByText('确认记住', { exact: true }).click()
  await page.locator('.taro-model__confirm').click()
  await expect(page.locator('.room-memory-row')).toContainText('喜欢先看例子再读定义')
  await page.reload(); await page.locator('.room-tabs').getByText('记忆 1', { exact: true }).click()
  await expect(page.locator('.room-memory-row')).toContainText('喜欢先看例子再读定义')
  await page.getByText('编辑', { exact: true }).click()
  await page.locator('input[placeholder="希望伙伴记住的偏好"]').fill('偏好先做一道例题')
  await page.getByText('确认修改', { exact: true }).click()
  await page.locator('.taro-model__confirm').click()
  await expect(page.locator('.room-memory-row')).toContainText('偏好先做一道例题')
  await page.getByLabel('删除记忆：偏好先做一道例题').click()
  await page.locator('.taro-model__confirm').click()
  await expect(page.locator('.room-memory-row')).toHaveCount(0)
  await page.reload(); await page.locator('.room-tabs').getByText('记忆 0', { exact: true }).click()
  await expect(page.locator('.room-memory-row')).toHaveCount(0)
  await page.getByText('秋庭澄', { exact: true }).first().click()
  await expect(page.locator('.room-name')).toHaveText('秋庭澄')
  await expect(page.locator('.room-tabs')).toContainText('记忆 0')
  await page.locator('.room-tabs').getByText('故事 1/4', { exact: true }).click()
  await expect(page.locator('.room-chapter').first()).toContainText('没有星星的值班夜')
  await expect(page.locator('.room-chapter').nth(1)).toContainText('第 3 次对话')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.screenshot({ path: '../docs/screenshots/h5/51-companion-story.png', fullPage: true })
  const other = await request.post('api/v1/user/account/register', { data: { username: `e2e_gesture_other_${Date.now()}`, password: 'Local-E2E-Only-1976' } })
  expect(other.status()).toBe(200)
  const otherToken = (await other.json()).data.token
  const isolated = await request.get('api/v1/companions/pink', { headers: { Authorization: `Bearer ${otherToken}` } })
  expect((await isolated.json()).data.memories).toHaveLength(0)
  expect(errors).toEqual([])
  await mkdir('../.local/sdlc/companion', { recursive: true })
  await writeFile('../.local/sdlc/companion/gesture-evidence.json', JSON.stringify({ runtime: 'Chromium + local API + isolated MySQL',
    checks: ['free-interior-placement', 'persist-position', 'drag-not-tap', 'tap-reaction', 'long-press-invite', 'invitation-no-paid-job', 'owned-memory', 'character-isolation', 'user-isolation', 'canonical-story', 'mobile-layout'], provider_calls: 0 }, null, 2))
})
